import csv

# Given data
data = [
    {
        "prompt": "I have two daughters. One is 8 years and other is 3.5 years old.\nElder one is little becoming inferior. She afraid of to asking questions. She is afraid that she will be scolded if she asks questions. That’s why she doesn’t ask questions. Whether it’s studies or other things. We are also at mistake as parents. What should I do? She can’t talk to anyone without fear. ",
        "completion": "You can try 3 things:\n1. Asking child why she is not asking questions? She could say that she did ask in the school but teacher scolded back. Whatever she says, you may listen. It is possible that she says no because she is scared. \n2. Then you may say her that you can ask any question to mommy. Mom will not scold her. Even if you did in the past, it will not repeat. This way, your daughter will have one person to whom she can ask questions. \n3. Check the school once whether they allow students to ask questions or not."
    },
    {
        "prompt": "I m moved by the story of 3 sisters playing chess,\nMy daughter is 4+ now and I have a dream for her to be a Olympian in martial arts i take her to taekwondo classes and get her to kick bags and all,\nWould love to get in touch with you as in what all can I add in her life for her to get excited about the game 🎯",
        "completion": "The key part is for your child to be interested and happy. There are too many cases of parents pushing children. So observe her and see her interest. And see where it goes"
    },
    {
        "prompt": "Please give me some point how parents can improve there behaviour with there kids so that they can have friendly relation with them and how a mother can control her anger. Or any suggestions if someone have already a bit complicated relation with there kid. I have to work on my anger in many situations i controlled it but yes there were situation that it got bursted on my son. Which I feel was not correct.",
        "completion": "It is so good that you recognise that it is your anger and nothing that your son is doing."
    },
    {
        "prompt": "He is getting from other family members because I live in joint family and no one understands what i am trying to say. Or make them understand about child behaviour ( comments like tu toh dheet hai kitna ziddi hota ja hai maa n bigad diya hai etc many) problem arises when my husband doesn't understand the same. There is chapter of your where u mentioned parents busy hai bacha unke liye drink banane gaya and the parent reaction was exactly my husband reaction. There is lot straight forward parenting is going on with ruhaan and the word \"NO\" is used hell lot of time almost a whole day.",
        "completion": "you are trying and you care. Research proves that the child needs only one good relationship which believes in him and helps. That’s all it takes."
    },
    {
        "prompt": "Thoughts on parents and their previous trauma and its impact on children’s growth. We all know it hampers, so more than how I would like to understand how parents can avoid bringing their patterns and traumas while raising their children.",
        "completion": "Being with children is a chance to heal ourselves, if one can be conscious"
    },
    {
        "prompt": "My daughter is 19 mnths. But jab usko me koi chij nai deti hu ya uski koi zid Puri nai kti hu tou wo mujhe hit karti haiShe is just 19 mnths..how can I control this behaviourYa kabhi kabhi wo masti me b mujhe hit kar deti hai.\n\nI tell her hitting noo..nd wo khud b bolti hai hitting nooo..but not regularly..but spcly wen i don't listen to her",
        "completion": "Meherr ji - sorry for the late reply. Aapki beti choti hai. Is umar mein kuch na milne pe kaise behave karna hai bachon ko pata nahin hota. Emotion pe kaabu nahin hota. Lekin bachon ka bhi maarna rok sakte hai. Thoda time laga ke.\nKabhi bhi jiss cheez ke liye bacha hit kar raha hai woh puri nahin karni kyonki phir bachey ko lagta hai ke maarne se cheez milegi. So a no means a no. But pyaar se.\nAap calm aawaaz mein usko bol sakti hai - No using hands and feet. Mujhe lagti hai. Same line hi humein baar baar use karni hai.\nPhir Aap uski feeling ko acknowledge karo. Ke aapko woh chahiye. Haan? Mujhe pata hai. Mujhe pata hai aapko aacha lagta hai. Lekin maarne se kabhi nahin milega. Mummy loves you. \nBachon ke nervous system ko touch karne se calmnes milti hai. Unko touch karke pyaar se mana karenge to baat samajne ka chance zyada hai.\nYeh sab karke hum apne bachey ko sikha rahe hai ke how to be in control of their emotions. Yeh imp learning sabse pehle maa baap se hi aati hai :-)\nLots of love to your family ❤️"
    },
    {
        "prompt": "So the thing is, I’ve a 1 year old. When he was hit by something or got hurt or when he falls down, immediately my family members start hitting that object so that he calms down. I’m not liking this behaviour. They are failing to understand a point that eventually he starts blaming someone else or something else if anything goes wrong instead of regulating his emotions. No matter how many times I try to express this to my family members, they brush it off and say that they’ll learn slowly when they get bigger😐",
        "completion": "Try this - rather than advising. Ask them questions to chat up, don’t go with a closed mind. For eg why do you hit the other thing, where did you learn this from"
    },
    {
        "prompt": "How I can make my child wake up early to school. She just wakes up at 7 am where her school is for 8. And top of that she is a picky eater. Needs atleast 40 min of time for breakfast itself. I start waking her up from 6. This is becoming our daily thing. I'm helpless and showing frustration on her. I want to change this situation. What can I do",
        "completion": "i faced similar thing with my daughter. We did couple of things\n- slept on time the previous day\n- spoke to our daughter that we need to leave for school at X time. And before that she has to\n- get ready\n- eat food\n\nAfter that, my daughter completely changed. She does needs some reminder. But 90% is gone because she knows that if she doesn’t get ready and her school has a cut off time of 8.45am. And if she doesn’t get school on time, she will have to spend a day at home when all her friends will be at school. So actually, there is sense of agency. And this is what we need to activate in every child. Their own sense of agency to do things. We can’t keep pushing them. Then the sense of agency goes away. So you need to take a step back and let the child be responsible."
    },
    {
        "prompt": "my son is 9 yrs old he loves only old songs like mere saamne waali kidki types? I don't noe whether his choices will affect further!",
        "completion": "It’s ok I guess. If you want him to explore other genres then you can play them at home and see if he picks up something!\nAnd in the same genres are so many nice songs like Tera Mujhse hai pehle ka nata koi, uthein sab ke kadam. You could explore them as well.\n\nWhen the same kid becomes 14-15 years old, stop listening to his parents and only does what his friends do. So parents tell him you only do what your friends are telling. Can’t you think for your ownself.\n\nAnd now when your child is younger. when he is different and we think why is he different and not like other kids. So a lot of these things are in the heads of parents."
    },
    {
        "prompt": "I am a mother to a 3.5 year old girl. Recently she threw a tantrum. She wants to watch tv for the whole day. Also she therw the food in the plate in anger. For not letting her watch tv. Cried for hours and then stopped on her own. Feeling guilty because I beat her out of frustration. Was continuous crying and not ready to listen at all. How to help her understand. This was the first time she did this... Please help.",
        "completion": "what has happened has happened. She lost her cool, you lost yours 🙂 that’s ok.\nYou can give her a hug and say sorry to her for hitting. And tell her that you love her. Young kids can’t make the connection between vyavahar and maar.\nGoing forward your solution lies in agreeing on say 30 min everyday for TV rule. And following it religiously so that she can trust you. This will 100% stop ❤️"
    },
    {
        "prompt": "Very good way of explaining that we don’t have to be worried about tantrums..\nbut on the other hand what about those kids who are always obedient and never assert on wanting a particular thing. My 3 year old is and has always been “that good child” who always listens me. Always submits. I try not to show domination. But how can I make this child a strong head and decisive adult who knows what she wants and how to get it.",
        "completion": "Humera ji - we can do two things- follow our child which means to observe her without correcting etc- look at the environment particularly ourselves to see that we are not unknowingly creating an environment which is creating submission for e.g. are other women in the house submissive to men, or does someone talk harshly to her\n\nOverall there is place in the world for all kinds of us. And she seems like a wonderful natured girl."
    },
    {
        "prompt": "I hav found that u understand d subconscious mind of d child .\nI hav a request pls can u tell when to start preschool or play school for kids - i mean what age n everyone tells it's normal if they cry for first few days .\nI want to kno how does psychology works of a child ....\nI couldn't see my child crying her heart out bcoz she dint wanted to go n everyone told me I'm over pampering her n let her cry ....\nIt will b gr8 if u could spare some time n answer my query",
        "completion": "Vishakha ji, kids cry for a lot of reasons.- first few days, they can have separation anxiety. If you have it when you go to drop her, she will sense it. So imp for you to be calm- say you are leaving from your house for school and she says mumma i dont want to go, starts to cry a bit and to keep her calm you say we are not going to school but then you do go to school, she starts crying again. So our lying is contributing to her crying. We should 100% stop lying.It is imp to see that the school has the right environment for the child. That means - place to play, free play, to run around, loving teachers. A good play school can help a child make friends and be comfortable in the company of others apart from parents.What is most imp for your child to know is that you are there for her. And that you will come back to pick her. Once she feels secure she will be ok"
    },
    {
        "prompt": "Hi Harpreet,😀 I've started following your channel very recently after it popped up as a suggestion while scrolling. I am glad that it showed up!😃 because I really like the way you are sharing your thoughts, analysis of child behavior patterns and also sharing important parenting tips in detail which are much needed for this gen working parents. I'm conciosuly trying my best to inclucate Montenssori method of teaching and raising a chid with gentle and respectful parenting. Din't know how simple and effetive these methods are in raising an independent and empathetic generation. Though very exhausting compared to traditional parenting method we were brought up with, it's very rewarding as it's scientific and extremely respectful way of treating another individual. Thank you soo much ❤️for making time to share your knowledge on this platform to help us new gen parents stay more educated on these topics! 😇on a side note, I keep getting asked questions many times by my family and friends to justify the parenting style I'm trying to follow and insisting them also to practice, and without thorough research and understanding myself I feel it hard to be convinced to implement any practice.one such is kid hitting and I have understood how yelling or scolding the child for hitting doesn't help in their growth and informing them that it's hurting others, giving them options to use their hands for other activities than hitting, taking them to safe space , giving them time to calm down etc.. slowly has actually helped in making my child to hit less.. but the question I got back is \" how do you handle when your child gets hit by some other child at school? how will you prevent it? by making him all empathetic and gentle won't he be too sensitive? shoudl he not hit back if someone is bullying him or hitting him?\" can you please help me in getting answers to these. I've tried searching but not got any solid answers yet. If you already have reels on this, can you please share it or any other links anytime you are free .. it'd be very helpful ! 😇",
        "completion": "Nandhitha - thank you for your message. And glad you are thinking about all this. on hitting our children this is a video you can see. on bullying and how should a child tackle it this is a hindi 5 min podcast you could hear.\n\nWhat you are doing is right - we dont need to hit the person who is hitting us - there are other ways. Adults (teachers etc) can be involved as well👍\n\nA loving child is not a sensitive child. When we hit a child the only thing a child learns is 'the person hitting me does not love me' and he bottles up anxiety."
    },
    {
    "prompt": "I just saw your video on Linkedin about negative effects on children due to hitting them which is really informative and insightful. Can you also answer this question, if a child has already been hit many times in past during the age of 6-12 by the parent, how a parent can revive his relationship with that child? The child has grown already stubborn and manipulative over these years.",
    "completion": "What you are describing is a situation which could take a lot of effort to revive. I will strongly suggest to take help of a therapist or child psychologist. TheFamilytree in Delhi is one place I know which can help. I am sure there are other good places. Apart from considering therapy personally I would have started by saying sorry to the child. And finding connection time with him. Go on a vacation with the child. That’s the start. To build trust again. Which will take time. "
  },
  {
    "prompt": "Hi i m mother of 7 yrs old girl....just few days back I was started follow ur page. ...as I see u shared parenting hood tips....bt i want to share with u about my daughter she is 7 yrs old she is hyper active child.....as I live in joint family so she is pampering child also....bt because of over pamper Ness she is never listen to me even a single tym...i do many tyms repeatations. And at last I feel anger or sme tyms fed-up .....as I consult with doctor past 2 yrs back about her so doctor said she is having ADHD problem.....LikeForwardCopyReportSometimes I dnt understand stand to .....teach them her gud nd bads...... because of over pampering makes her ziddi type bacha.....she is never ready to listen me.....plz share ur some valuable tips nd tricks hw i deal with herScreen time is in whole day only one hour\nBecause of cold weather she is playing only indoor games......\nNd part of pampering in u cn say that like said anything to her for good or i m not allowed her for something so she will go to her grandparents and said to them muma mana kr rhi hai",
    "completion": "Avneet ji - saw your message.\n- how much screen time does she get\n- how much time with nature outdoors does she get\n- when you say pampered in joint family can you explain this?\n\nAvneet looks like the main thing you have to work on is not the child\nBut your relationship with other elders in the house\nBecause what is imp is that all the adults are on the same page\nOtherwise the child will take advantage\nThis can be hard but that is the one solution if you want the best for your child.\nAvneet - this does look like a situation where you could take help of a counsellor/doctor also. So please do. TheFamilytree in Delhi is one good place I know. Also time outside is critical, with nature. For the child. If you can spend that with your child, that would help"
  },
  {
    "prompt": "Screen time is in whole day only one hour\nBecause of cold weather she is playing only indoor games......\nNd part of pampering in u cn say that like said anything to her for good or i m not allowed her for something so she will go to her grandparents and said to them muma mana kr rhi hai",
    "completion": "Avneet looks like the main thing you have to work on is not the child\nBut your relationship with other elders in the house\nBecause what is imp is that all the adults are on the same page\nOtherwise the child will take advantage\nThis can be hard but that is the one solution if you want the best for your child.\nAvneet - this does look like a situation where you could take help of a counsellor/doctor also. So please do. TheFamilytree in Delhi is one good place I know. Also time outside is critical, with nature. For the child. If you can spend that with your child, that would help"
  },
  {
    "prompt": "I’ve a 4 year old girl and she doesn’t want to speak to new people. She gets very quiet in front of any person except me and her dad. Even at school she’s a quiet child. She’s not expressive and have to play the guessing game all the time. I don’t know how to improve on that.",
    "completion": "Please see this"
  },
  {
    "prompt": "Hii, my son is 5.5 years old. He does not like to go for any structured classes. For example, he would love to play football casually but he resists going to a class...Please help me understand why...The problem is also that if he is not going for any extracurricular activities then it becomes very difficult to pass his time. In that case, he looks for screens for entertainment.\nAlso, I see all other boys his age doing basketball, dance, swimming, painting classes and it makes me very worried.",
    "completion": "Hi Karishma, that’s ok. He’s young. He will tell you when he is ready. Don’t ask him and let him be and enjoy seeing him :-)\n\nGot it. Screen time has to be fixed. Say 30 min daily. Post that no screen time. This is critical to do. Only then you would see and he will find what is interesting to him. He might say he is bored and that's ok. But screen has to stop. Also, to make the transition smoother you can try going with him below initially."
  },
  {
    "prompt": "I am mother of 9-year-old. I wanted to ask what to do if my daughter is not following 30 min mobile time and one candy a day rule. Like she hides and do things",
    "completion": "Chitrangada ji rules are best set with the child. For eg, it is possible she is seeing 2 hours a day. So there has to be a discussion with the child in a playful way that I am worried about your eyes and that we are not going outdoors to play. So I am thinking 15 min only. And she will say no no 30 min. And then you together agree on something.."
  },
  {
    "prompt": "What is the right age for pre-school?",
    "completion": "There is no right age. You should think about why you want to send the kid to pre-school and does the pre-school offer that. Makes sense?"
  },
  {
    "prompt": "I have started following recently must say all video have something to learn n unlearn for parents.. I need your help on a situation when my baby 2 yr old plays with 2 more kid one is 2.5 n 3 yr old . I have observed while playing lets say for toy other kid has tried hitting him he just cried loudly i dont know what to say in this situation.. Actually one of parent already asked to say sorry to my baby. But this has been happening frequently.. every time i will not be there .. sometimes nanny will be there..I have told that if it happens again just calm him down and distract from them .",
    "completion": "Hi Alisha, if the situation is not dangerous to tell the kids of the kids you could just remove yourself from the situation and let them sort it out. If you think this is happening again and again you can use telling other kids - no using hand and feet - you could tell their parents too. These are all chotu kids who find it difficult to control emotions.\n\nKids can’t understand why sorry at this age. If it’s not dangerous try next time not reacting at all. Observing."
  },
  {
    "prompt": "From which age we can teach coding to children and any good source for the same",
    "completion": "Coding requires understanding of logic and maths. You could wait till the age of 7-8 before introducing it. A fun way to do it is"
  },
  {
    "prompt": "I have a two years old boy and a new born girl.. due to my pregnancy he stayed somewhat away from me and stayed with his grandparents. Now his total behaviour has changed and whatever I have taught before or the character everything changed.. most of the time he spends in front of tv.. he is not listening to me.. now he knows that his grandparents gives whatever he asks for and mom won’t give unwanted things.. how can I bring back his old characters and how to reduce screening time??",
    "completion": "congratulations on your new child. And it is good that you are thinking about this. And about your child's behaviourThere are two things for you to do- get on the same page as a family - you and grandparents need to be on the same page. So that rules of the house are same so that child cannot go to someone else and manipulate- secondly stop screen from today. Talk to everyone, agree on say 30 min screen time for day and a time say 2:00 pm. Then talk to your child , tell him screen is not good for long hours and we will have only 30 min. if there is crying let there be crying, it will pass, you don't need to react. finally spend some time with him, take our 15 min a day when you and him can do something together without your daughter. Let him feel loved"
  },
  {
    "prompt": "Will you please help me with addiction of you tube in my 6year old? Nothing constructive but silly videos of gamers playing n vocalising everything they do in it n that too in a weird voice n language 🤯I have tried manier times but kids just don’t listen! I can’t scold him every time",
    "completion": "Hi Cherry, the key is time. You can set a 30 min limit for watching. And ensure that is followed. As long as the content is not harmful and abusive it’s ok. What is key is not to have over exposure. You can do that through house rules.\n\nCherry - if there is a house rule. The rule needs to be followed. This is basic that we need to set as parents in the house. You can discuss with the child and set it together. But there is no alternative to this. The consequences of too much mobile or TV are severe"
  },
  {
    "prompt": "I loved the video on tantrums….. I could resonate so much with it. What I had learned so far from others was not to change your stance after the child’s tantrum….. otherwise the child will learn that show tantrum and things get his way…… but my experience use to tell me that my child genuinely doesn’t want to do that particular thing…… I always get in dilemma….. now what to do… so I try to negotiate and end it there. Like maybe play for 10 more minutes or clean it after 10 minutes…. Or sometimes just change the topic\nI don’t know what is right or what is wrong…… but after watching your video I am assured tantrums are not all that bad.",
    "completion": "I think the key is for rules to be implemented consistently but with some flexibility if reqFor eg my daughters cartoon time is 30 min. So if I go at the end of 30 min she will say let me finish it and we see 2-3 min together and then close it👍 But I could also go after 25 min and then at 30 it will close. Same with play time. It ends at 7. And if I go to pick her up from friends place she will say I want to play more. So the thing is to ask how much 2 more min and she will say no no 5. Which is ok. But the best is to go 5-10 min early say at 6:50. If you see we do the same thing when we are playing with our friends, ke chal yaar 5 min aur baithte hai"
  },
  {
    "prompt": "Iam mother of 4 year old boy and like other parents iam also curious to know about my kids brainI have one question if you can answer that in any of your new video podcastSee we are very well off parents now we can afford everything to our child i always hear that you are spoiling your child by providing him everythingMostly i send on toys because we don't give him tv and mobile strictly no in our house so I just buy new toys blocks so that he should learn analysis and he can keep himself busy....and i also like toys...i teach him how to play like make a construction site and then make a fire station. Kindly guide about these things",
    "completion": "Hi Pragati, a few toys once in a while is ok. When we buy toys we out source the creativity of our child to the toy manufactured. The more children can play with natural stuff the better, but a few toys are always ok. I hope this helps"
  },
  {
    "prompt": "Iam a doctor by profession and i love your stuff...my husband is in merchant Navy so as a result we can't give him much time...But we live in countryside area so we are giving him gardens to play and many kids around making friends....and lots of natural activities are here so in a way trying keep him happy and occupied",
    "completion": "If you have less time then Ensure the time is consistent. That is imp to raise a secure child"
  },
  {
    "prompt": "my son is 4 years old in nursery he is good in his activities...some people are telling me to jump him to KG II as he is doing well...❤️. As doctor I know that there is no limit to studies iam against making him jump....want to know your opinion about this",
    "completion": "What your child needs is time to play freely. Whatever offers that is great. From this freedom of playing will come the discipline to do bigger things"
  },
  {
    "prompt": "have a 3.5 year old and she absolutely refuses to talk to other kids and doesn’t even play with other kids - in school and in the building. I tried asking her why and I don’t force her.. but what can I do?How can I help her make friends",
    "completion": "She’s young and feels secure around you. So let it be, give her unconditional love and enjoy the time."
  },
  {
    "prompt": "I am unable to take it when my child do silly mistakes in her exams. she doesn’t want to study at all. I get very very worried about this. And many times is scold her and the whole environment becomes bitter.I experience anger, worry, irritation at the same time.\nAnd i cant stop scolding her id i get angry.I know i am doing wrong but just cant stop myself.How yo overcome this behaviour?",
    "completion": "So good to see your message. Nothing better than self-realization. I am glad you asked this question. \n\nHere is a 5 min podcast that you could listen to - please hear To not get irritated means you will have to change the way your brain is wired. Right now your neurons in the brain are connected in a certain way and several things that your child does become triggers.Here are a few suggestions I have- meditation should help - Isha Yoga has a course called Inner Engineering which I will encourage you to take and practise- you could think about the trigger situation beforehand and think about how you will behave differently. Essentially re-wire the brain by thinking differentlyThis will be hard but 100% possible. Also see drbecky good inside handle once on insta. she posts lots of content around this. Thanks once again for asking and glad you wrote"
  },
  {
    "prompt": "Telling him to treat me as his friend n share everything about his curiosity... N explained about what good n what bad .. but my husband is worried that he is still young for all these n his thinking will change now on. Hence v r confused. Though we explained everything he may watch it again and again in some or the other way..\n\nDoes this affect his thinking n innocenceShall v take him to any psychologist so they can guide him better to understand. By the way thanks a lot for ur time n advice. This means a lot.",
    "completion": "these videos can be hurtful so we have to find ways to limit on device and at the same time not express shock if we see this happening. There is nothing wrong with the child. the idea is to protect him from overexposure.\n\nEverything we see or do affects our brain. So you should definitely find a way to stop it without him feeling fearful of you"
  },
  {
    "prompt": "my daughter is 9 years old she often tells lies even for unnecessary things.N she gets caught every time and I try explaining to her ABT truth and lies.But still she repeats it. I’m\n not sure how to correct her or will she get self-corrected when she grows up? Can plz throw some light on this topic too?",
    "completion": "can you share what kind of lies she tells?"
  },
  {
    "prompt": "My daughter studies in 3 std.. Recently,she came with a star put on her hand and she said mam gave her for her good performance in the test.. Honestly i believed her ..but later when I was asking in detail then she opened up n said it was her who friend who had put tht star and not mam..In fact, everytime she lies, she get caught easily .But still she is not able to stop tht habit.But so far it's harmless kind of things and I have a strong feeling tht she does to get appreciated ..I spoke to her n number of times to make her understand..Though at that point of time she says she understood and she keeps repeating it . Can you please guide me on how to tackle this?",
    "completion": "So most of times she is doing this to get appreciation from you or to feel good about herself? More examples?"
  },
  {
    "prompt": "Mera 1 sawal hai\nMy daughter is 15 months old and she loves to play with water In fact I think mostly all the kids of her age love this.\nSo me soch rahi thi uske swimming class join karu.\nKya abhi se ye theek rahega?\nI think she will have fun. Hum jab bhi beach pe jate hai wo pani dekh ke bahot hi Khush Ho jati hai.\nCan you share your thoughts ?",
    "completion": "Please take her more to water and the pool! Swimming can be learnt at any ageThe thing is if the teacher is not great she might not enjoy the instructionsJust don’t push her. Let her enjoy. \n\nSee the story on this page."
  },
  {
    "prompt": "Still struggling this with.. I don't know how to make this this understand to my daughter she is 4 and she just wants to win and if not than huge meltdown.\n\nShare some tips to implement this enjoy the process",
    "completion": "Don’t react to the meltdown :-)\n\nJust say it’s ok. Did you fun playing the game. I had fun playing with you, sometimes you win, sometimes I win. But I love playing with you."
  },
  {
    "prompt": "So these days I have a struggle with my 6 year old son, who doesn't understand that when someone is saying no to something, he has to stop there and not impose himself. For example, after school he wants to play but the other kids are tired , not to play and they refuse, he would force them to play and eventually hit, which has become like a complaint for him from the other parents. Please help me how can I make my son understand that he has to play within his limits.",
    "completion": "Well your child wants to play that’s great actually!He is not looking to go see more tv mobile but actually play! A few things that come to my mind - I wish parents would leave kids alone to solve this. It will get self solved.But given other parents have a concern on hitting, you can talk to your child when he is calm thatYou want to play rightRight?He nods. And sometimes others don’t want to play, right. He nodsHow does that make you feelAngryI understandI understand you want to play so badly. But we will not use our hands and feetWe will not use our hands and feet. Anothe replace to do this conversation is just before he is going to play with his friends. Also you can find him alternate ways to spend energy, outdoor play etc. Other friends who have more energyYour child is fantastic! He just wants to play :-) You only have to help him express his feelings better. And all of this is assuming that his mobile time, screen time is <30 min a day. Otherwise gadgets can keep our mind underregulated and stimulated. Lots of love to your playful kid!"
  },
  {
    "prompt": "My daughter is also very shy..i mean she is not calm she interact with her age(7year) kids but badose bat karneme hich hichati hai..bus chand chuninda logoke samnehi vo open up hoti hai .\n\n\nActually AAP Jo bol rahe ho vo sab samjh me ata hai ..sab sahi hai ..but fir baki log is tarah se nahi samjhte...vi kehte aap ki beti bat hi nahi karti.karna chahiye...ya fir dirctly use kuch dat dete hai..aur vo bahot ro deti hai...n hum log un logoko aise usase bat na kijiye aise keh bhi nahi sakte",
    "completion": "Could you hear the podcast?\nBaaki logon ko bhi yeh suna do. Aur na samjhe to bhool jao un logon ki baaton koLikeForwardCopyUnsendWhat matters for you here is your daughter"
  },
  {
    "prompt": "Watched your video on importance of peers in choosing a school. Could not relate more. These are exactly the circumstances we went through. We finally ended up choosing the Old CBSE School with a reputed brand but often wonder if we made the right choice…\nHave you done any videos on choosing between International boards and CBSE, would help us a lot.",
    "completion": "Hi Sakshi, I haven't done on CBSE vs international. What do you think are the differences?"
  },
  {
    "prompt": "Im one of parent who made my son n daughter watch mobile or tv while eating...now im feeling very guilty of doing this thing again n again every day...\nWhat should i do i want to change this habit...",
    "completion": "You can just stop now :-)Tell them we are going to stop eating with mobileThey will resist but in 4-5 days they will agree. Lead with love. Tell them it’s your fault you allowed mobile with food and we have to stop coz it’s not good for eyes"
  },
  {
    "prompt": "Namakar mobile dikha ker khana na khilaye ye kafi acha tha , lekin bacha puchta hai papa kyu khana khate hai tv dekhte hue ya ghar ke sabhi log khana kyu khate hai tv dekhte hue mera koi jawab nahi thakyo ki bacha humse hi shikhta hai , aur bade hi iss baat ko nazar andaz ker dete haighar ke aur logo ko kaise samjhaye ki tv na dekhe. ya tv mai aise content na dekhe jisse bache ko taklif ho , nahi sunte ghar wale.\n\nItna easy nahi hai sab kuch , as a mother i am taking best care … but baki log apni zimedari bhul jate hai , conservative Indian society mai , if i utter single word , dekho isko sara gyan aya hai jaise bache humne bade kiye hi nahi hai ,Mother is the culprit ache se khilati nahi ho bache ko , kitli patli hai , sanskar nahi shikhaye , as mother is responsible for everything, videos ache hai apke , lekin there is problem in indian mentality. Apni puri life laga di bache ko bada kerne mai did all sacrifices lekin i am responsible for everything jitna bhi acha ker lo dekho ye hai wo haii",
    "completion": "What you are saying Shweta is the truthYour child's question is fair. It was asked in her house. We had to get on the same page. Now we finish food as a family together and then watch TV. Being on the same page with other adults is the most imp thing. But that can be hard, I agree with you."
  },
  {
    "prompt": "I have 3 years old kid , I’m really confused to which school to join himWe located at north Banglore Yelahanka. Can u suggest me a good school with good education",
    "completion": "Gowthami ji, I don't know that area. But I am sure you will decide the right school. Pick a pre school where he can play freely, has outdoors :-)"
  },
  {
    "prompt": "Hello sir, can you please help… m mother of 3.5 year old boy…M preparing for state service and also pursuing llb… cz of studies m not able to give time to ma son…Actually Abi Tak till 3 years may uske sath full time ti… per padhai kerti ti n he use to play around me… ab Maine llb admission liya hai so college jati hu … then again competitive exam ki preperation… in sub may time nhi Dey pa Rahi Hu…Mera beta kami mujse dur nhi rehta tha… per this time for summer vacation he went to his grandparents place… waha Jane k baad usne mujse ek bar video call ker baat nhi ki… n cal kiya to bolta hai may Tumhare pass kabi nhi aaunga🥹 I don’t like you🥺Muje Samj nhi aa raha… Maine kaha galti ki… may studies kerti hu per deti hu time ..LikeForwardCopyReportCan you please advice 🙏",
    "completion": "Hi Rupali jiDon’t take what kids say so seriously :-)As long as you are joyful and you can spend some time with your son say 30 min morning 30 min evening you will build a bondBut if one is absent or if one keeps correcting the child then the child will look for love where he will getLikeForwardCopyUnsendYou should be happy he had grandparents where he is joyful as well"
  },
  {
    "prompt": "Sir I really wanna asked u ki aapki baby kis school me jati hai.. now here is ans.. so i want to asked u .. aapne Montessori school chose karte time uss school me kya kya quality dekhi thi.. i am asking u bcoz kuch din maine pehle aapse pucha tha isi se related qus.. main uss time bhi yahi janna chahti thi ki … ek school ko usski fees se judge karu ya kaise… kaise main ek acha montessari school select karu.. bcoz ye toh mera clear hai issko Montessori bejhna hai .. par koun sa montessari school best hai ye kise pata lagauLikeReport\nReplied to your storyAnd are u still continue ur kid with Montessori in class 1 or u have switched her to normal school or ib or any other",
    "completion": "Hi Varnika, my daughter still goes to Montessori. It's a small school but it is till grade 6. Grade 4 for eg has 4 kids. I spoke to the founder of the school and had a discussion. My idea was to understand if she understands children, which she did better than me. So I put my daughter in the school. Along with that walking into the environment had a positive feeling with the way it was laid out. It was bright, clean, big windows with light streaming in. So both of them combined. If you read a bit on Montessori then you will be able to understand better. For e.g. you could pick one of the following books Montessori method (first two chapters are hard), Discovery of childhood or Secret of childhood - read chapter 4 and 5. Also imp to note that there are schools which say Montessori but don't teach that well, and there are normal board schools where the principal is great and she ensures love for learning is inculcated in kids despite the board."
  },
  {
    "prompt": "Ye mere pass jyada rehta hAgr iske papa uthay to b mere pass bhagta hQ mera ye hKi father baby ka trust kaise gain kreLikeForwardCopyReportMtlb kuch tips",
    "completion": "Two things\n- it is normal for a child to come to you, mothers tend to spend more time and child is more comfortable so let him come :-) enjoy the time\n- for father baby trust, you take out some time for yourself, tell the child I am going out for some time and the father can play in the house or can take child out to garden.This will give them time together and bonding will increase"
  },
  {
    "prompt": "How to improve focus in 5 year kid...my kid is like more distracted during eating , selecting some time toy , if we say do excecies he will do one or two time n done n find somthing different. I am little bit concerned about hisFocus on one thing",
    "completion": "Children's brain learn through movement not through sitting down. So allow him to have a lot of time for free play + observe your child without interfering + take him to nature. And have no screen time or screen time of <30 min.And it's ok na to move about while eating"
  },
  {
    "prompt": "Hi Harpreet, I really like what you share about parenting. There is one thing that constantly bothers me. The awareness that we have today about what to do and what not to do with kids does not go well with previous generation. This causes a huge clash of opinions, ego and everything. I moved out of a joint family setup few days back with my 2 year old. Though some times i feel guilty , i also feel confident that he will be in a label-free, judge-free and emotionally safe environment.LikeForwardCopyReportWhat are your observations or thoughts in a joint family setup?",
    "completion": "Every joint family is different. Joint families allow flexibility for the mother and father as there can be many caretakers/parentsbut all adults can have different views so there can be clashesto live in a joint family the key is that the adults are on the same page regarding kids. So a joint family can be good or bad based on the different people.LikeForwardCopyUnsendJust keep in mind to find a playschool which let him be, and don't force teaching"
  },
  {
    "prompt": "Hi sir,\nMy child is 5and half year old. right now he is in ukg,, I'm not satisfied with the education that's the school provided, so i planned to change the school,, i choosed a better school, &my son attended the written test,, and he failed coz of Reading, my son is new to reading language,, old school didn't started any reading program yet,, the new school told me, they give admission to UKG or else you both will suffer, 😒\nAm crying inside coz i spoiled my child kg.\nIm repeating him ukg nxt year.\nHe will be 5year and 10month when he enter ukg.\nI spoiled his 1year of his life.\nIs my decision right for him??\nPls replyy\nMy friends say he Will he okay when he goes up in school\nBt my both parents say let him get a good base?\nIm confused\nFeeling 😒 i spoiled his one year",
    "completion": "Hi Afsal ji (I hope I got the name right)Your child is young. And school's are run as a business. So don't pay too much attention to them. What is imp is that your child has enough free time to play, learns joyfully and is able to pursue his interests. Rather than be pressurised to do things.When he is 40 years old this 1 year that you are worrying about won't matter at all :-)❤️so don't worryyou love your son, that is so apprant. and that is the thing that child needs the most. Just don't let that love convert to anxiety!"
  },
  {
    "prompt": "My 4year daughter is not able to identify colour. Even after telling 10 times it is yellow colour she would say orange colour. What should I do",
    "completion": "Hi Chhaya, First of all don't worry :-)You don't need to ask her 10 times. She need not feel that because she sees the world differently than you, she is lesser than othersAll of us see the world differentlyIt is possible that she is colour vision deficient. And that's ok.You can do the below test. Please read and see---To give yourself a basic indication of whether there might be a problem with your child’s colour vision, get a sheet of white paper and a basic set of colouring pencils – at least 12 different colours but including green, red, brown, orange, blue, purple and grey. Use mid-range shades, not too pale or too dark– and shade an area of about 2cm by 2cm of each colour onto the paper. Make sure that the colours are in random order and that you don’t have all the reds or greens together, but do place red, green and brown adjacent to each other. Take the paper and your child to an area with good natural light (but not a bright light, artificial light or strong sunlight) and make up a fun game which involves asking your child to identify all of the colours on the sheet. Do not show them each colour individually, they must be able to see all of the colours at the same time.If your child shows signs that they are not sure whether a colour is red, green, brown, purple, blue or grey, there is a reasonable chance that they are red/green colour blind. Before you start ask them which colours are the easiest for them to identify. You should expect a red/green colour-blind child to be able to identify bright blue and yellow (they can identify these colours by brightness and shade). Make sure you include these colours so that they do not get the impression that they aren’t clever enough for the game. Just do this once with love. And share back. Again don't make your child feel that just because she sees the world differently something is wrong with her!"
  },
  {
    "prompt": "Can you please tell us how to improve child spoken English. Plz guide",
    "completion": "By talking to them. The more practise they get the better it is. You can also get Alexa and the child can talk to Alexa and have funLikeForwardCopyUnsendThe idea is that the child needs practise and the right environment will give him this practise"
  },
  {
    "prompt": "HelloPlease tell me correct age of admission for my daughter in play schoolLikeForwardCopyReportAt what age should I send her",
    "completion": "All ages are good. And no age is best. You can send whenever you feel your child is ready. The idea is that the child finds comfort and security with parents and goes to playschool to gain new experiences.LikeForwardCopyUnsendJust keep in mind to find a playschool which let him be, and don't force teaching"
  },
  {
    "prompt": "Hi Harpreet, watching your videos the contents you sharing are amazing. I have a baby she is turning 2 years in . She is picky eater I have tried varieties of food and 2 hours gap for each meal but nothing worked. She weighs 9.2 kgs. Doctor says she has to improve . Not getting how to feed her. She likes only raw vegetables n fruits. Please help me to find some solution",
    "completion": "She likes all the right things!\nLet her eat what she likes, give more of it!\nWhat is imp is that she feels loved and does not feel judged that something is wrong with her because she likes fruits and vegetables\ndon't worry\nlet her be\nand then see in 2 months\n\n\n\ndoes she see screen?\ndoes she eat food with screen?\ndoes she go out to play?"
  },
  {
    "prompt": "Hey i am new follower of your page. Just wanted to ask you one que. My 6 years son always want a new toy. He went his frd's house he come to know about his frd's new toy. He will come home and he will ask me for the same toy. Its only not toy... if anybody surrounding him gets new bag pencile eraser anything... HE WANTS MEANS HE WANTS. How to tacket this? What should make him understand? Pls help me\n\nI make him understand we dont need this. We can save money instead. But he dosent understand. How to handle this? What should i say to him?LikeForwardCopyUnsend\n\nIts started before 6 months. I try not to give him but sometimes i had to give it\n\nI know i have made lot of mistake but now how will i reapir it.\nVery less time 45 mins of screen time\n1 hr outdoor time\nNot that much shopping we do\nI am homemaker. I give him my undevided 1hur. We do drawing painting and craft.\n\nTo give into trantrums.\n\nSee i have made him undrstands that u r small will give everything but once u get younger and if you dont get your desired things u will face disappoinment. I dont want it.But now ill make a rule to buy one toy in a month.LikeForwardCopyReportThank you so much. You are kind and helpfull👍🏻😊",
    "completion": "So what do you do then when he wants? What does he do? Why do you think this habit has come to this stage?\n\ndo you remember when did it start. when he doesn't understand then what do you do?\n\nsurethe idea is to understand the kid is okhe is just doing what his environment has trained him to do: how much screen time does he have?how much outdoor time?are there others in the house who do a lot of shopping?how much time do you get with him daily? or your partner?\n\nYou seem to have done the right things. Why do you think you have made mistakes :-)\n\nSo you can solve that now\n\nThe idea is talk to him, give him a hug and say I have given in to tantrums but I am not going to now. Because I love you and I think this is leading you to the wrong direction. Secondly make simple rules of the house. For eg every month we will buy one thing. Or he gets pocket money of 500 rs to do whatever he wantsMake rules with him with love. This should be solved!\n\nKids can’t understand such long term stuff. Have a simple rule and follow!Please tell me what happensOnce you decide don’t give in to tantrums. Deal with love but firmness"
  }
]

# Define the CSV file path
csv_file_path = "output_file.csv"

# Write data to CSV file
with open(csv_file_path, mode="w", newline="", encoding="utf-8") as file:
    fieldnames = data[0].keys()  # Assuming all entries have the same keys
    writer = csv.DictWriter(file, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(data)

print("CSV file successfully generated.")
